"use client";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/utility/Navbar";
import NavbarMobile from "@/components/utility/NavbarMobile";
import CursorTrailCanvas from "@/components/utility/cursor-trail-canvas";
import useLenis from '@/hooks/useLenis';
import favicon from "@/assets/favicon.ico"
import CurrentTime from "@/components/ui/CurrentTime";
import { Providers } from "@/components/utility/ThemeProvider"
import SocialMediaLinks from "@/components/utility/SocialMediaLinks";
import Footer from "@/components/utility/Footer";
import {ScrollProgressDemo} from "@/components/utility/ScrollProgress"


const metadata: Metadata = {
  title: "Akash Kumar",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useLenis();
  return (
    <html lang="en" suppressHydrationWarning> 
      <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      <body className="antialiased overflow-x-hidden relative bg-[--Background] dark:bg-[--Background] select-none "> 
        <ScrollProgressDemo />
        <Providers>
        <CurrentTime />
          <Navbar />
          <NavbarMobile />
          <div className="hidden md:block  fixed bottom-1 right-12  h-48 w-16  z-[999]">
            <SocialMediaLinks/>
          </div>
          <CursorTrailCanvas className="pointer-events-none fixed inset-0 -z-10 h-full w-full hidden md:block " />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
